### ISSUE TITLE
API nevrací správně v RoomEndpointu

### ISSUE THREAD

**Issue by Nightraw** [lukx1/Chatter#2]
**URL**: http://78.102.218.164:8080/api/Room/GetUsersInRoom
**Request**: {"Login":"Nightraw","Password":"_secret_","ID":"2"}
**Response**: Všichni Useři co jsou v JAKÉKOLIV roomce.
**Bonus**: Je jedno jaký je ID v requestu

**URL**: http://78.102.218.164:8080/api/Room/GetRoomsWithUser
**Request**: {"Login":"Nightraw","Password":"_secret_","ID":"18"}
**Response**: Všechny roomky.

**Comment by lukx1** [comment]
Oba opraveny. Server nepoužíval where klauzuli k filtraci nevhodných výsledků a tím způsobil zamoření vrácených dat neplatnými údaji.
